 INSERT INTO REPORTING_DB.CONFIG.REPORT_CONFIG (
  CONFIG_ID, REPORT_NAME, REPORT_TYPE, TRIGGER_TYPE, PRIORITY
 ) VALUES (
     'TEST_ADHOC_20250912', 'Test ADHOC Report', 'TEST', 'ADHOC', 1
);

INSERT INTO REPORTING_DB.CONFIG.REPORT_CONFIG (
        CONFIG_ID, REPORT_NAME, REPORT_TYPE, TRIGGER_TYPE, PRIORITY
    ) VALUES (
        'TEST_ADHOC_20250913', 'Test ADHOC Report After Fix', 'TEST', 'ADHOC', 1
    );